defaults:
  - default

# Pose-only finetuning for OPV2V cylindrical coop (2x A800).
max_num_of_imgs_per_gpu: 8  # num_views=4 -> max batch size = 2 samples/GPU
accum_iter: 1

epochs: 5
warmup_epochs: 1

lr: 1e-04
min_lr: 1e-06
weight_decay: 0.0

save_freq: 1
keep_freq: 1
eval_freq: 999
print_freq: 20

disable_cudnn_benchmark: false

submodule_configs:
  # Freeze everything except pose prediction modules.
  encoder:
    lr: 0
  info_sharing:
    lr: 0
  dpt_feature_head:
    lr: 0
  dpt_regressor_head:
    lr: 0
  ray_dirs_encoder:
    lr: 0
  depth_encoder:
    lr: 0
  depth_scale_encoder:
    lr: 0
  cam_rot_encoder:
    lr: 0
  cam_trans_encoder:
    lr: 0
  cam_trans_scale_encoder:
    lr: 0
  scale_head:
    lr: 0
  scale_adaptor:
    lr: 0

  pose_head:
    lr: ${train_params.lr}
    min_lr: ${train_params.min_lr}
    weight_decay: 0.0
  pose_adaptor:
    lr: ${train_params.lr}
    min_lr: ${train_params.min_lr}
    weight_decay: 0.0
